playground_frontend:
  name: "frontend"
  replicaCount: 1
  labels: 
    app: "frontend"
  template:
    labels: 
      app: "frontend"
  container:
    name: frontend
    image: oleksiidn/usct-ui
    imageTag: 0.0.1
    imagePullPolicy: IfNotPresent
  profiles: "container"
  service:
    name: "frontend"
    type: ClusterIP
    port: 80
    targetPort: 80